import jsPDF from "jspdf";

import { reportService } from "@/services/report.service";

import { renderPdfHeader } from "./pdf-header";

import { renderFinancialSection } from "./pdf-financial";
import { renderCollectionSection } from "./pdf-collection";
import { renderPipelineSection } from "./pdf-pipeline";
import { renderAgingSection } from "./pdf-aging";
import { renderSalesSection } from "./pdf-sales";
import { renderSourceSection } from "./pdf-source";

export interface ExportReportOptions {

    companyName: string;

    generatedBy: string;

    reportTitle?: string;

    reportSubtitle?: string;

    fileName: string;

    exportAll: boolean;

    selectedReports: string[];

    orientation: "portrait" | "landscape";

    paperSize: "A4" | "Letter";

}

export async function exportReportPdf({

    companyName,

    generatedBy,

    reportTitle = "FECRM Business Report",

    reportSubtitle =
        "Customer Relationship Management Reporting",

    fileName,

    exportAll,

    selectedReports,

    orientation,

    paperSize,

}: ExportReportOptions) {

    ////////////////////////////////////////////////////////////

    const report =
        await reportService.getExportReportData();

    ////////////////////////////////////////////////////////////

    const doc = new jsPDF({

    orientation,

    unit: "mm",

    format: paperSize.toLowerCase(),

});

    ////////////////////////////////////////////////////////////

    renderPdfHeader(doc, {

        companyName,

        generatedBy,

        reportTitle,

        reportSubtitle,

    });

    ////////////////////////////////////////////////////////////

    let currentY = 95;

    ////////////////////////////////////////////////////////////

 if (
    exportAll ||
    selectedReports.includes("financial")
) {

    currentY =
        renderFinancialSection(
            doc,
            currentY,
            report.finance
        );

}

    ////////////////////////////////////////////////////////////

   if (
    exportAll ||
    selectedReports.includes("collection")
) {

    currentY =
        renderCollectionSection(
            doc,
            currentY,
            report.collection
        );

}

    ////////////////////////////////////////////////////////////

  if (
    exportAll ||
    selectedReports.includes("pipeline")
) {

    currentY =
        renderPipelineSection(
            doc,
            currentY,
            report.pipeline
        );

}

    ////////////////////////////////////////////////////////////
if (
    exportAll ||
    selectedReports.includes("aging")
) {

    currentY =
        renderAgingSection(
            doc,
            currentY,
            report.aging
        );

}

    ////////////////////////////////////////////////////////////

   if (
    exportAll ||
    selectedReports.includes("sales")
) {

    currentY =
        renderSalesSection(
            doc,
            currentY,
            report.sales
        );

}

    ////////////////////////////////////////////////////////////

    if (
    exportAll ||
    selectedReports.includes("source")
) {

    currentY =
        renderSourceSection(
            doc,
            currentY,
            report.sources
        );

}

    ////////////////////////////////////////////////////////////

    const pageHeight =
        doc.internal.pageSize.getHeight();

    const pageWidth =
        doc.internal.pageSize.getWidth();

    doc.setFontSize(9);

    doc.setTextColor(120);

    doc.text(

        "Generated by FECRM Reporting Module",

        pageWidth / 2,

        pageHeight - 10,

        {

            align: "center",

        }

    );

    ////////////////////////////////////////////////////////////

  const safeFileName =
    fileName
        .trim()
        .replace(/[\\/:*?"<>|]/g, "-");

doc.save(

    `${safeFileName}.pdf`

);

}