import jsPDF from "jspdf";

export interface PdfHeaderOptions {

    companyName: string;

    generatedBy: string;

    reportTitle?: string;

    reportSubtitle?: string;

}

export function renderPdfHeader(

    doc: jsPDF,

    options: PdfHeaderOptions,

) {

    const {

        companyName,

        generatedBy,

        reportTitle = "FECRM Business Report",

        reportSubtitle =
            "Customer Relationship Management Reporting",

    } = options;

    ////////////////////////////////////////////////////////

    const pageWidth =
        doc.internal.pageSize.getWidth();

    ////////////////////////////////////////////////////////

    const generatedDate =
        new Intl.DateTimeFormat(
            "en-GB",
            {

                day: "2-digit",

                month: "long",

                year: "numeric",

                hour: "2-digit",

                minute: "2-digit",

            }

        ).format(new Date());

    ////////////////////////////////////////////////////////
    // TOP BAR
    ////////////////////////////////////////////////////////

    doc.setFillColor(79, 70, 229);

    doc.rect(
        0,
        0,
        pageWidth,
        10,
        "F"
    );

    ////////////////////////////////////////////////////////
    // TITLE
    ////////////////////////////////////////////////////////

    doc.setFont(
        "helvetica",
        "bold"
    );

    doc.setFontSize(24);

    doc.setTextColor(30);

    doc.text(

        reportTitle,

        pageWidth / 2,

        24,

        {

            align: "center",

        }

    );

    ////////////////////////////////////////////////////////

    doc.setFont(
        "helvetica",
        "normal"
    );

    doc.setFontSize(11);

    doc.setTextColor(120);

    doc.text(

        reportSubtitle,

        pageWidth / 2,

        32,

        {

            align: "center",

        }

    );

    ////////////////////////////////////////////////////////

    doc.setDrawColor(220);

    doc.line(

        18,

        40,

        pageWidth - 18,

        40

    );

    ////////////////////////////////////////////////////////

    let y = 52;

    const left = 20;

    const right = pageWidth - 20;

    ////////////////////////////////////////////////////////

    doc.setFillColor(248, 250, 252);

    doc.roundedRect(

        left,

        y,

        right - left,

        34,

        2,

        2,

        "FD"

    );

    ////////////////////////////////////////////////////////

    const labelX = 28;

    const valueX = 70;

    ////////////////////////////////////////////////////////

    doc.setFontSize(10);

    ////////////////////////////////////////////////////////

    function drawRow(

        label: string,

        value: string,

        rowY: number,

    ) {

        doc.setFont(
            "helvetica",
            "bold"
        );

        doc.setTextColor(70);

        doc.text(

            label,

            labelX,

            rowY

        );

        doc.setFont(
            "helvetica",
            "normal"
        );

        doc.setTextColor(30);

        doc.text(

            value,

            valueX,

            rowY

        );

    }

    ////////////////////////////////////////////////////////

    drawRow(

        "Organization",

        companyName,

        y + 9

    );

    drawRow(

        "Generated By",

        generatedBy,

        y + 17

    );

    drawRow(

        "Generated On",

        generatedDate,

        y + 25

    );

    drawRow(

        "Module",

        "FECRM Reporting",

        y + 33

    );

    ////////////////////////////////////////////////////////

    y += 46;

    ////////////////////////////////////////////////////////

    doc.setDrawColor(225);

    doc.line(

        18,

        y,

        pageWidth - 18,

        y

    );

}